config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :users do
    resources :item_completes
  end
  resources :interests
  resources :bucket_list_items do
    resources :comments
  end

  root 'welcome#index'
  get 'welcome/map'

end

app/models/bucket_list_item.rb
class BucketListItem < ActiveRecord::Base

  has_many :user_bucket_list_items
  has_many :users, through: :user_bucket_list_items
  has_many :comments
  has_many :item_completes

  # validates :name, presence: true
  # validates :description, presence: true
  # validates :street_address, presence: true
  # validates :city, presence: true
  # validates :state, presence: true
  # validates :zip_code, presence: true

  aws_keys = if ['development', 'test'].include?(Rails.env)
    "#{Rails.root}/config/aws-keys.yml"
  else
    {
      bucket: ENV['S3_BUCKET_NAME'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
    }
  end
  has_attached_file :image,
   :styles => { :medium => "300x300>", :thumb => "100x100>" },
   :default_url => "/images/:style/missing.png",
   storage: :s3,
   s3_credentials: aws_keys,
   s3_permissions: 'authenticated-read',
   path: "items/:basename.:extension",
   s3_server_side_encryption: :aes256
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def s3_url(style=nil, expires_in=30.minutes)
    image.s3_object(style).url_for(:read, secure: true, expires: expires_in).to_s
  end

  def as_json(options={})
      super(:only => [:name, :description, :city, :state, :zip_code, :image_file_name, :id, :user_id, :bucket_list_item_id, :latitude, :longitude, :street_address],
            :include => {
              :comments => {:only => [:id, :content, :user_id, :bucket_list_item_id,],
              :include => {:user => {:only => [:first_name, :last_name, :email]}} }
      })
  end



end

app/controllers/bucket_list_items_controller.rb
class BucketListItemsController < ApplicationController

  before_action :set_bucket_list_item, only:[
    :show,
    :edit,
    :update,
    :destroy
  ]

  def index
    @bucket_list_items = BucketListItem.all
    respond_to do |format|
      format.json { render json: @bucket_list_items }
      format.html
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @bucket_list_item }
      format.html
    end
  end

  def create
    params[:bucket_list_item] = { image: params[:image], name: params[:name], description: params[:description], street_address: params[:street_address], city: params[:city], state: params[:state], zip_code: params[:zip_code], latitude: params[:latitude], longitude: params[:longitude]}

    @bucket_list_item = BucketListItem.new bucket_list_item_params
    @bucket_list_item.save
    respond_to do |format|
      format.json { render :json => @bucket_list_item }
    end
  end

  def update
    @users = @bucket_list_item.users
    @bucket_list_item.update bucket_list_item_params
    respond_to do |format|
      format.json do
        render json: @bucket_list_item
      end
      format.html {redirect_to bucket_list_items_path}
    end
  end

  def destroy
    @bucket_list_item.delete
    respond_to do |format|
      format.json { head :no_content }
      format.html {redirect_to bucket_list_items_path}
    end
  end

private
  def bucket_list_item_params
    params.require(:bucket_list_item).permit(
      :name,
      :description,
      :street_address,
      :city,
      :state,
      :zip_code,
      :image,
      :latitude,
      :longitude,
      :image_file_name,
      user_ids: []
      )
  end

  def set_bucket_list_item
    @bucket_list_item = BucketListItem.find params[:id]
  end
end

app/helpers/bucket_list_items_helper.rb
module BucketListItemsHelper
end

app/views/bucket_list_items/create.html.erb
<h1>BucketListItems#create</h1>
<p>Find me in app/views/bucket_list_items/create.html.erb</p>

app/views/bucket_list_items/destroy.html.erb
<h1>BucketListItems#destroy</h1>
<p>Find me in app/views/bucket_list_items/destroy.html.erb</p>

app/views/bucket_list_items/edit.html.erb
<h1>BucketListItems#edit</h1>
<p>Find me in app/views/bucket_list_items/edit.html.erb</p>

app/views/bucket_list_items/index.html.erb
<h1>BucketListItems#index</h1>
<%= link_to 'Add Bucket List Items', new_bucket_list_item_path =%>
<br>
<% @bucket_list_items.each do |bucket_list_item| %>
<%= bucket_list_item.name =%>
<br>
<%= bucket_list_item.street_address =%>
<br>
  <%= image_tag bucket_list_item.s3_url =%>
  <br>
<% bucket_list_item.users.each do |user| %>
<%= user.email %>
<br>
<% end %>
<br>
<% end %>

app/views/bucket_list_items/new.html.erb
<h1>BucketListItems#new</h1>
Add New Bucket List Item:
<%= render 'form' =%>

app/views/bucket_list_items/show.html.erb
<h1>BucketListItems#show</h1>
<p>Find me in app/views/bucket_list_items/show.html.erb</p>

app/views/bucket_list_items/update.html.erb
<h1>BucketListItems#update</h1>
<p>Find me in app/views/bucket_list_items/update.html.erb</p>